name: mindaprice_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8
  geolocator: ^12.0.0
  geocoding: ^2.2.0
  google_fonts: ^6.0.0
  intl: ^0.18.1
  http: ^1.2.2
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^17.2.2
  cloud_functions: ^4.6.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  adaptive_icon_background: "#0B5D1E"
  adaptive_icon_foreground: assets/icon.png
  image_path: "assets/icon.png"

flutter_native_splash:
  background_image: "assets/background.png"
  color: "#D0E7D2"
  image: assets/icon.png
  android: true
  ios: false
  android_12:
    color: "#D0E7D2"
    image: assets/icon.png