// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQq4RL1rhhV5Pn4-ct16kfkoqwc6vAKM',
    appId: '1:995020752129:web:a8d407ebad1e1fed30c700',
    messagingSenderId: '995020752129',
    projectId: 'mindaprice-zw',
    authDomain: 'mindaprice-zw.firebaseapp.com',
    storageBucket: 'mindaprice-zw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jPZEiE68xRi-sweDJqNpRBRLB5bGiN8',
    appId: '1:995020752129:android:a937377f33ce1d1530c700',
    messagingSenderId: '995020752129',
    projectId: 'mindaprice-zw',
    storageBucket: 'mindaprice-zw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLvk6go2-AS6bHIba74ZacAmkfuc7Gq8',
    appId: '1:995020752129:ios:55e70ed7472208b230c700',
    messagingSenderId: '995020752129',
    projectId: 'mindaprice-zw',
    storageBucket: 'mindaprice-zw.firebasestorage.app',
    iosBundleId: 'com.example.mindapriceTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLvk6go2-AS6bHIba74ZacAmkfuc7Gq8',
    appId: '1:995020752129:ios:55e70ed7472208b230c700',
    messagingSenderId: '995020752129',
    projectId: 'mindaprice-zw',
    storageBucket: 'mindaprice-zw.firebasestorage.app',
    iosBundleId: 'com.example.mindapriceTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJQq4RL1rhhV5Pn4-ct16kfkoqwc6vAKM',
    appId: '1:995020752129:web:0d8f3ab5d63bb42130c700',
    messagingSenderId: '995020752129',
    projectId: 'mindaprice-zw',
    authDomain: 'mindaprice-zw.firebaseapp.com',
    storageBucket: 'mindaprice-zw.firebasestorage.app',
  );
}
